name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Set up Node.js
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run compile
