name: Publish

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@163217dfcd28294438ea1c1c149cfaf66eec283e
      - name: Set up Node.js
        uses: actions/setup-node@aca7b64a59c0063db8564e0ffdadd3887f1cbae5
      - name: Install dependencies
        run: npm ci
      - name: Publish
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
